language: ruby
bundler_args: --without development --deployment
cache: bundler
env:
  - TEST_SUITE=unit
rvm:
  - ree
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ! 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'
  - bundle config build.gherkin --with-cflags=-w
before_script:
  - export RAILS_ENV=test
  - cp -f config/travis/database.yml config/database.yml
  - bundle exec rake db:drop db:create db:migrate
  - bundle exec rake tests:suite:prepare:$TEST_SUITE
  - export RUBY_HEAP_MIN_SLOTS=1000000
  - export RUBY_HEAP_SLOTS_INCREMENT=1000000
  - export RUBY_HEAP_SLOTS_GROWTH_FACTOR=1
  - export RUBY_GC_MALLOC_LIMIT=1000000000
  - export RUBY_HEAP_FREE_MIN=500000
script: bundle exec rspec spec
branches:
  only:
    - master
    - staging
    - upgrade
notifications:
  hipchat:
    rooms:
      - 48a2260ad2549b2915d4deb954d6ea@416311
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} (<a href="%{build_url}">Details</a>/<a href="%{compare_url}">Change view</a>)'
    format: html
