@m17 @global_deal_changes
Feature: Deals global changes

  Scenario: As PM I should be able to share the short deal info on the social networks (facebook, twitter, linkedin)

  Scenario: I should be able to set normal price and discounted

  Scenario: I should be able to set social media short deal info

  Scenario: I should see the saving % (calculated) in browse deals for deals with discounted price

  Scenario: I should be able to see the slug for the view deal's details url

  Scenario: I should be able to see the total leads generated by deal

  Scenario: As I admin I can change the number of generated leads from a deal

