development:
  paypal_email: seller_1292244681_biz@gmail.com
  paypal_secret: secret
  paypal_cert_id: LHHDMRYKCAU8U
  paypal_url: "https://www.sandbox.paypal.com/cgi-bin/webscr"

test:
  paypal_email: test@example.com
  paypal_secret: testsecret
  paypal_cert_id: 123456789
  paypal_url: "test/paypal/url"

production:
  paypal_email:
  paypal_secret:
  paypal_cert_id:
  paypal_url: "https://www.paypal.com/cgi-bin/webscr"

staging:
  paypal_email: seller_1292244681_biz@gmail.com
  paypal_secret: secret
  paypal_cert_id: LHHDMRYKCAU8U
  paypal_url: "https://www.sandbox.paypal.com/cgi-bin/webscr"

testing:
  paypal_email: seller_1292244681_biz@gmail.com
  paypal_secret: secret
  paypal_cert_id: LHHDMRYKCAU8U
  paypal_url: "https://www.sandbox.paypal.com/cgi-bin/webscr"