development:
  paypal_email: seller_1292244681_biz@gmail.com
  paypal_secret: secret
  paypal_cert_id: 9BRAS4HRS3EXS
  paypal_url: "https://www.sandbox.paypal.com/cgi-bin/webscr"
  paypal_api_email: seller_1292244681_biz_api1.gmail.com
  paypal_api_password: 1292244690
  paypal_api_key: AUVjzPkoCJAf1p9N6vEssI4hIPVVA6XjBKUpjBLNogHCfw29dQWFK6bF
  paypal_api_url: "https://api-3t.sandbox.paypal.com/nvp"
  quickpay_window_url: "https://secure.quickpay.dk/form/"
  quickpay_email: "admin@fairleads.com"
  quickpay_merchant_id: "32466257"
  quickpay_secret: "dsjnM6rG4TUqZ2S81YQ3WK9989iLFm3v2Jplu12I7R3PH9xB3Db8fV1761ey5Xgh"
  quickpay_api_key: "9T1yRB9IJfuVc4x28v3Y8445Kp1jr3lt2Z78sNU1696A5i1GPk6gnH56Ee3D37Lb"

test:
  paypal_email: test@example.com
  paypal_secret: testsecret
  paypal_cert_id: 123456789
  paypal_url: "test/paypal/url"
  paypal_api_email: seller_1292244681_biz_api1.gmail.com
  paypal_api_password: 1292244690
  paypal_api_key: AUVjzPkoCJAf1p9N6vEssI4hIPVVA6XjBKUpjBLNogHCfw29dQWFK6bF
  paypal_api_url: "https://api-3t.sandbox.paypal.com/nvp"
  quickpay_email: "qp_seller32434234@nbs.com"
  quickpay_secret: "dj38dhj39d3dx3tdsg3d2e2ef23rd232"
  quickpay_api_key: "f1ds2wk39fej329ew29rk92392"

production:
  paypal_email: admin@fairleads.com
  paypal_secret: i1knTfEsql5724S1MCX5QgV1Me0xXw
  paypal_cert_id: JTL4K5CBZA9HA
  paypal_url: "https://www.paypal.com/cgi-bin/webscr"
  paypal_api_email: "admin_api1.fairleads.com"
  paypal_api_password: "8T7H3529UWE775HK"
  paypal_api_key: "ACeUiIrWgxnYT8IMF-wJwdgl.sjEA5RpsViJ6SPhHx2TT4xITs8R8CKt"
  paypal_api_url: "https://api-3t.paypal.com/nvp"
  quickpay_email: "admin@fairleads.com"
  quickpay_secret: "dsjnM6rG4TUqZ2S81YQ3WK9989iLFm3v2Jplu12I7R3PH9xB3Db8fV1761ey5Xgh"
  quickpay_api_key: "9T1yRB9IJfuVc4x28v3Y8445Kp1jr3lt2Z78sNU1696A5i1GPk6gnH56Ee3D37Lb"

staging:
  paypal_email: seller_1292244681_biz@gmail.com
  paypal_secret: secret
  paypal_cert_id: 9BRAS4HRS3EXS
  paypal_url: "https://www.sandbox.paypal.com/cgi-bin/webscr"
  paypal_api_email: seller_1292244681_biz_api1.gmail.com
  paypal_api_password: 1292244690
  paypal_api_key: AUVjzPkoCJAf1p9N6vEssI4hIPVVA6XjBKUpjBLNogHCfw29dQWFK6bF
  paypal_api_url: "https://api-3t.sandbox.paypal.com/nvp"
  quickpay_email: ""
  quickpay_secret: ""
  quickpay_api_key: ""

testing:
  paypal_email: seller_1292244681_biz@gmail.com
  paypal_secret: secret
  paypal_cert_id: 9BRAS4HRS3EXS
  paypal_url: "https://www.sandbox.paypal.com/cgi-bin/webscr"
  paypal_api_email: seller_1292244681_biz_api1.gmail.com
  paypal_api_password: 1292244690
  paypal_api_key: AUVjzPkoCJAf1p9N6vEssI4hIPVVA6XjBKUpjBLNogHCfw29dQWFK6bF
  paypal_api_url: "https://api-3t.sandbox.paypal.com/nvp"
  quickpay_window_url: "https://secure.quickpay.dk/form/"
  quickpay_email: "admin@fairleads.com"
  quickpay_merchant_id: "32466257"
  quickpay_secret: "dsjnM6rG4TUqZ2S81YQ3WK9989iLFm3v2Jplu12I7R3PH9xB3Db8fV1761ey5Xgh"
  quickpay_api_key: "9T1yRB9IJfuVc4x28v3Y8445Kp1jr3lt2Z78sNU1696A5i1GPk6gnH56Ee3D37Lb"