development:
  paypal_email: seller_1292244681_biz@gmail.com
  paypal_secret: secret
  paypal_cert_id: 9BRAS4HRS3EXS
  paypal_url: "https://www.sandbox.paypal.com/cgi-bin/webscr"
  paypal_api_email: seller_1292244681_biz_api1.gmail.com
  paypal_api_password: 1292244690
  paypal_api_key: AUVjzPkoCJAf1p9N6vEssI4hIPVVA6XjBKUpjBLNogHCfw29dQWFK6bF
  paypal_api_url: "https://api-3t.sandbox.paypal.com/nvp"

test:
  paypal_email: test@example.com
  paypal_secret: testsecret
  paypal_cert_id: 123456789
  paypal_url: "test/paypal/url"
  paypal_api_email: seller_1292244681_biz_api1.gmail.com
  paypal_api_password: 1292244690
  paypal_api_key: AUVjzPkoCJAf1p9N6vEssI4hIPVVA6XjBKUpjBLNogHCfw29dQWFK6bF
  paypal_api_url: "https://api-3t.sandbox.paypal.com/nvp"

production:
  paypal_email: admin@fairleads.com
  paypal_secret: i1knTfEsql5724S1MCX5QgV1Me0xXw
  paypal_cert_id: JTL4K5CBZA9HA
  paypal_url: "https://www.paypal.com/cgi-bin/webscr"
  paypal_api_email: "admin_api1.fairleads.com"
  paypal_api_password: "8T7H3529UWE775HK"
  paypal_api_key: "ACeUiIrWgxnYT8IMF-wJwdgl.sjEA5RpsViJ6SPhHx2TT4xITs8R8CKt"
  paypal_api_url: "https://api-3t.paypal.com/nvp"

staging:
  paypal_email: seller_1292244681_biz@gmail.com
  paypal_secret: secret
  paypal_cert_id: 9BRAS4HRS3EXS
  paypal_url: "https://www.sandbox.paypal.com/cgi-bin/webscr"
  paypal_api_email: seller_1292244681_biz_api1.gmail.com
  paypal_api_password: 1292244690
  paypal_api_key: AUVjzPkoCJAf1p9N6vEssI4hIPVVA6XjBKUpjBLNogHCfw29dQWFK6bF
  paypal_api_url: "https://api-3t.sandbox.paypal.com/nvp"

testing:
  paypal_email: seller_1292244681_biz@gmail.com
  paypal_secret: secret
  paypal_cert_id: LHHDMRYKCAU8U
  paypal_url: "https://www.sandbox.paypal.com/cgi-bin/webscr"
  paypal_api_email: seller_1292244681_biz_api1.gmail.com
  paypal_api_password: 1292244690
  paypal_api_key: AUVjzPkoCJAf1p9N6vEssI4hIPVVA6XjBKUpjBLNogHCfw29dQWFK6bF
  paypal_api_url: "https://api-3t.sandbox.paypal.com/nvp"