development:
  access_key_id: AKIAJUCLH3EUZBE7SS6A
  secret_access_key: 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
  bucket: fairleads/development

production:
  access_key_id: AKIAJUCLH3EUZBE7SS6A
  secret_access_key: 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
  bucket: fairleads/production

staging:
  access_key_id: AKIAJUCLH3EUZBE7SS6A
  secret_access_key: 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
  bucket: fairleads/staging