#!/usr/bin/env ruby

vendored_cucumber_bin = Dir["#{File.dirname(__FILE__)}/../vendor/{gems,plugins}/cucumber*/bin/cucumber"].first
if vendored_cucumber_bin
  load File.expand_path(vendored_cucumber_bin)
else
  unless ENV['NO_RUBYGEMS']
    require 'rubygems'
    require 'bundler/setup'
  end
  require 'cucumber'
  load Cucumber::BINARY
end
